#!/bin/sh
# aios (エントリースクリプト)
# License: CC0
# OpenWrt >= 19.07, Compatible with 24.10.0

SCRIPT_VERSION="2025.02.16-00-00"
echo -e "\033[7;40mUpdated to version $SCRIPT_VERSION aios \033[0m"

DEV_NULL="${DEV_NULL:-on}"
# サイレントモード
# export DEV_NULL="on"
# 通常モード
# unset DEV_NULL

# 基本定数の設定 
INPUT_LANG="${@:-}"
BASE_WGET="${BASE_WGET:-wget -q -O}"
# BASE_WGET="${BASE_WGET:-wget -O}"
BIN_PATH="/usr/bin/aios"

BASE_URL="${BASE_URL:-https://raw.githubusercontent.com/site-u2023/aios/main}"
BASE_DIR="${BASE_DIR:-/tmp/aios}"

COMMON_SH="$BASE_DIR/common.sh"
CACHE_DIR="${CACHE_DIR:-$BASE_DIR/cache}"
LOG_DIR="${LOG_DIR:-$BASE_DIR/logs}"
DEBUG_MODE="${DEBUG_MODE:-false}"

#########################################################################
# aios: 
#########################################################################
chmod_aios() {
chmod +x "$BIN_PATH"  # aios に実行権限を付与
}

#########################################################################
# delete_aios: 既存の aios 関連ファイルおよびディレクトリを削除して初期化する
# 必要に応じて
#########################################################################
delete_aios() {
    rm -rf "${BASE_DIR}"
}

#########################################################################
# make_directory: 必要なディレクトリ (BASE_DIR) を作成する
#########################################################################
make_directory() {
    mkdir -p "$BASE_DIR" "$CACHE_DIR" "$LOG_DIR"
}

#################################
# 共通ファイルのダウンロードと読み込み
#################################
download_common() {
    if [ ! -f "${BASE_DIR}/common.sh" ]; then
        ${BASE_WGET} "${BASE_DIR}/common.sh" "${BASE_URL}/common.sh" || {
            echo "Failed to download common.sh"
            exit 1
        }
    fi

    # 読み込み
    source "${BASE_DIR}/common.sh" || {
        echo "Failed to source common.sh"
        exit 1
    }
}

#########################################################################
# print_banner: 言語に応じたバナー表示 (messages.db からメッセージ取得)
#########################################################################
print_banner() {

    echo
    echo -e "\033[1;35m                    ii i                              \033[0m"
    echo -e "\033[1;34m         aaaa      iii       oooo      sssss          \033[0m"
    echo -e "\033[1;36m            aa      ii      oo  oo    ss              \033[0m"
    echo -e "\033[1;32m         aaaaa      ii      oo  oo     sssss          \033[0m"
    echo -e "\033[1;33m        aa  aa      ii      oo  oo         ss         \033[0m"
    echo -e "\033[1;31m         aaaaa     iiii      oooo     ssssss          \033[0m"
    echo

    echo
    color magenta "                    ii i"
    color blue    "         aaaa      iii       oooo      sssss"
    color cyan    "            aa      ii      oo  oo    ss"
    color green   "         aaaaa      ii      oo  oo     sssss"
    color yellow  "        aa  aa      ii      oo  oo         ss"
    color red     "         aaaaa     iiii      oooo     ssssss"
    echo

    printf "%s\n" "$(color white "$(get_message "MSG_BANNER_DECCRIPTION")")"
    printf "%s\n" "$(color white "$(get_message "MSG_BANNER_NAME")")"
    printf "%s\n" "$(color red "$(get_message "MSG_BANNER_DISCLAIMER")")"
}

#################################
# インストール (不要なら削除可)
#################################
packages() {
# ttyd
install_package ttyd yn hidden
install_package luci-app-ttyd yn hidden

# openssh-sftp-server
install_package openssh-sftp-server yn hidden
}

#################################
# メイン処理
#################################
chmod_aios
delete_aios
make_directory
download_common
check_option "$INPUT_LANG"
print_banner
packages # 必要に応じて
download openwrt-config.sh
